spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${secrets.DB_URL}
    username: ${secrets.DB_ID}
    password: ${secrets.DB_SECRET}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${secrets.G_CLIENT_ID}
            clientSecret: ${secrets.G_CLIENT_SECRET}
            scope:
              - email
              - profile
webClient:
  baseUrl: ${secrets.OPENBANKING_URL}
openbanking:
  api:
    client-id: ${secrets.K_CLIENT_ID}
    client-secret: ${secrets.K_CLIENT_SECRET}
    redirect-uri: ${secrets.K_REDIRECT_URI}