name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  
defaults:
  run:
    working-directory: ./tikkle-be
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Add permission
        run: chmod +x gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build -Pspring.profiles.active=application-prod
        working-directory: ./tikkle-be

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Code Deploy - BackEnd
        run: >
          aws deploy create-deployment --application-name TIKKLE
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name TIKKLE-group

      - name: Code Deploy - FrontEnd
        uses: game-builder/setup-aws-cli@v1
        with:
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ap-northeast-2
      - name: Upload to S3 Bucket
        run: aws s3 sync ./tikkle-fe s3://my-bucket --delete
env:
  DB_ID: ${{secrets.DB_ID}}
  DB_PASSWORD: ${{secrets.DB_SECRET}}
  G_CLIENT_ID: ${{secrets.G_CLIENT_ID}}
  G_CLIENT_SECRET: ${{secrets.G_CLIENT_SECRET}}
  K_CLIENT_ID: ${{secrets.K_CLIENT_ID}}
  K_CLIENT_SECRET: ${{secrets.K_CLIENT_SECRET}}
  K_REDIRECT_URI: ${{secrets.K_REDIRECT_URI}}
  OPENBANKING_URL: ${{secrets.OPENBANKING_URL}}
